# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: "ubuntu:latest"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: "apt-get update && sudo apt-get install apt-transport-https ca-certificates gnupg software-properties-common wget"
      - run:
          name: obtain cmake copy key 
          command: "wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null"
      - run:
          name: add the repo to the sources list and update 
          command: "sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal main'
sudo apt-get update"
      - run:
          name: Install CMAKE
          command: "sudo apt-get install cmake"
      