# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


jobs:
    build:
        docker:
            - image: "ubuntu:latest"
        steps:
            - checkout
            - run:
                  name: Installing SUDO
                  command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'